name: Publish Library
run-name: Publish Library

on:
    push:

jobs:
    build:
        name: Build NPM Project
        runs-on: ubuntu-latest
        container: node:alpine
        steps:
            - name: Clone Repository
              uses: ztimson/actions/clone@develop

            - name: Install & Build
              run: npm i && npm run build
              working-directory: lib

            - name: Upload to Registry
              uses: ztimson/actions/npm/publish@develop
              with:
                  working-directory: lib

            - name: Upload to NPM
              uses: ztimson/actions/npm/publish@develop
              with:
                  owner: ztimson
                  registry: https://registry.npmjs.org/
                  token: ${{secrets.NPM_TOKEN}}
                  working-directory: lib
